// tslint:disable
/**
 * geopot
 * Monitoring SSH login attempts and geolocating remote hosts who failed to login and gathering used credentials.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: razj@josefraz.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI } from '../runtime';
import type { OperationOpts, HttpQuery } from '../runtime';
import type {
    ModelsConnection,
    ModelsHourlyStat,
    ModelsLatLng,
    ModelsNumberValue,
    ModelsTopEntry,
} from '../models';

export interface GetHourlyStatsRequest {
    hours?: number;
}

export interface GetRecentConnectionsRequest {
    limit?: number;
}

export interface GetTopCountriesRequest {
    limit?: number;
}

export interface GetTopPasswordsRequest {
    limit?: number;
}

export interface GetTopUsernamesRequest {
    limit?: number;
}

/**
 * no description
 */
export class StatsApi extends BaseAPI {

    /**
     * Get all latitude and longitude pairs from the database
     * All Latitude and Longitude
     */
    getAllLatLng(): Observable<Array<ModelsLatLng>>
    getAllLatLng(opts?: OperationOpts): Observable<AjaxResponse<Array<ModelsLatLng>>>
    getAllLatLng(opts?: OperationOpts): Observable<Array<ModelsLatLng> | AjaxResponse<Array<ModelsLatLng>>> {
        return this.request<Array<ModelsLatLng>>({
            url: '/api/stats/allLatLng',
            method: 'GET',
        }, opts?.responseOpts);
    };

    /**
     * Get connection counts per hour for the last N hours
     * Hourly Stats
     */
    getHourlyStats({ hours }: GetHourlyStatsRequest): Observable<Array<ModelsHourlyStat>>
    getHourlyStats({ hours }: GetHourlyStatsRequest, opts?: OperationOpts): Observable<AjaxResponse<Array<ModelsHourlyStat>>>
    getHourlyStats({ hours }: GetHourlyStatsRequest, opts?: OperationOpts): Observable<Array<ModelsHourlyStat> | AjaxResponse<Array<ModelsHourlyStat>>> {

        const query: HttpQuery = {};

        if (hours != null) { query['hours'] = hours; }

        return this.request<Array<ModelsHourlyStat>>({
            url: '/api/stats/hourly',
            method: 'GET',
            query,
        }, opts?.responseOpts);
    };

    /**
     * Get the number of connections in the last 24 hours
     * Last 24 Hour Connections
     */
    getLast24HourConnections(): Observable<ModelsNumberValue>
    getLast24HourConnections(opts?: OperationOpts): Observable<AjaxResponse<ModelsNumberValue>>
    getLast24HourConnections(opts?: OperationOpts): Observable<ModelsNumberValue | AjaxResponse<ModelsNumberValue>> {
        return this.request<ModelsNumberValue>({
            url: '/api/stats/last24HourConnections',
            method: 'GET',
        }, opts?.responseOpts);
    };

    /**
     * Get the N most recent connection attempts
     * Recent Connections
     */
    getRecentConnections({ limit }: GetRecentConnectionsRequest): Observable<Array<ModelsConnection>>
    getRecentConnections({ limit }: GetRecentConnectionsRequest, opts?: OperationOpts): Observable<AjaxResponse<Array<ModelsConnection>>>
    getRecentConnections({ limit }: GetRecentConnectionsRequest, opts?: OperationOpts): Observable<Array<ModelsConnection> | AjaxResponse<Array<ModelsConnection>>> {

        const query: HttpQuery = {};

        if (limit != null) { query['limit'] = limit; }

        return this.request<Array<ModelsConnection>>({
            url: '/api/stats/recentConnections',
            method: 'GET',
            query,
        }, opts?.responseOpts);
    };

    /**
     * Get the server\'s own info
     * Self Info
     */
    getServerInfo(): Observable<ModelsConnection>
    getServerInfo(opts?: OperationOpts): Observable<AjaxResponse<ModelsConnection>>
    getServerInfo(opts?: OperationOpts): Observable<ModelsConnection | AjaxResponse<ModelsConnection>> {
        return this.request<ModelsConnection>({
            url: '/api/stats/selfInfo',
            method: 'GET',
        }, opts?.responseOpts);
    };

    /**
     * Get top N countries by connection count
     * Top Countries
     */
    getTopCountries({ limit }: GetTopCountriesRequest): Observable<Array<ModelsTopEntry>>
    getTopCountries({ limit }: GetTopCountriesRequest, opts?: OperationOpts): Observable<AjaxResponse<Array<ModelsTopEntry>>>
    getTopCountries({ limit }: GetTopCountriesRequest, opts?: OperationOpts): Observable<Array<ModelsTopEntry> | AjaxResponse<Array<ModelsTopEntry>>> {

        const query: HttpQuery = {};

        if (limit != null) { query['limit'] = limit; }

        return this.request<Array<ModelsTopEntry>>({
            url: '/api/stats/topCountries',
            method: 'GET',
            query,
        }, opts?.responseOpts);
    };

    /**
     * Get top N passwords by usage count
     * Top Passwords
     */
    getTopPasswords({ limit }: GetTopPasswordsRequest): Observable<Array<ModelsTopEntry>>
    getTopPasswords({ limit }: GetTopPasswordsRequest, opts?: OperationOpts): Observable<AjaxResponse<Array<ModelsTopEntry>>>
    getTopPasswords({ limit }: GetTopPasswordsRequest, opts?: OperationOpts): Observable<Array<ModelsTopEntry> | AjaxResponse<Array<ModelsTopEntry>>> {

        const query: HttpQuery = {};

        if (limit != null) { query['limit'] = limit; }

        return this.request<Array<ModelsTopEntry>>({
            url: '/api/stats/topPasswords',
            method: 'GET',
            query,
        }, opts?.responseOpts);
    };

    /**
     * Get top N usernames by usage count
     * Top Usernames
     */
    getTopUsernames({ limit }: GetTopUsernamesRequest): Observable<Array<ModelsTopEntry>>
    getTopUsernames({ limit }: GetTopUsernamesRequest, opts?: OperationOpts): Observable<AjaxResponse<Array<ModelsTopEntry>>>
    getTopUsernames({ limit }: GetTopUsernamesRequest, opts?: OperationOpts): Observable<Array<ModelsTopEntry> | AjaxResponse<Array<ModelsTopEntry>>> {

        const query: HttpQuery = {};

        if (limit != null) { query['limit'] = limit; }

        return this.request<Array<ModelsTopEntry>>({
            url: '/api/stats/topUsernames',
            method: 'GET',
            query,
        }, opts?.responseOpts);
    };

    /**
     * Get total connection count
     * Total connection count
     */
    getTotalConnectionCount(): Observable<ModelsNumberValue>
    getTotalConnectionCount(opts?: OperationOpts): Observable<AjaxResponse<ModelsNumberValue>>
    getTotalConnectionCount(opts?: OperationOpts): Observable<ModelsNumberValue | AjaxResponse<ModelsNumberValue>> {
        return this.request<ModelsNumberValue>({
            url: '/api/stats/totalConnections',
            method: 'GET',
        }, opts?.responseOpts);
    };

    /**
     * Get count of unique countries
     * Unique Countries Count
     */
    getUniqueCountryCount(): Observable<ModelsNumberValue>
    getUniqueCountryCount(opts?: OperationOpts): Observable<AjaxResponse<ModelsNumberValue>>
    getUniqueCountryCount(opts?: OperationOpts): Observable<ModelsNumberValue | AjaxResponse<ModelsNumberValue>> {
        return this.request<ModelsNumberValue>({
            url: '/api/stats/uniqueCountryCount',
            method: 'GET',
        }, opts?.responseOpts);
    };

    /**
     * Get count of unique IP addresses
     * Unique IP Address Count
     */
    getUniqueIPCount(): Observable<ModelsNumberValue>
    getUniqueIPCount(opts?: OperationOpts): Observable<AjaxResponse<ModelsNumberValue>>
    getUniqueIPCount(opts?: OperationOpts): Observable<ModelsNumberValue | AjaxResponse<ModelsNumberValue>> {
        return this.request<ModelsNumberValue>({
            url: '/api/stats/uniqueIpCount',
            method: 'GET',
        }, opts?.responseOpts);
    };

}
