// tslint:disable
/**
 * geopot
 * Monitoring SSH login attempts and geolocating remote hosts who failed to login and gathering used credentials.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: razj@josefraz.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI } from '../runtime';
import type { OperationOpts, HttpHeaders } from '../runtime';
import type {
    ModelsValue,
} from '../models';

/**
 * no description
 */
export class StatsApi extends BaseAPI {

    /**
     * Get total connection count
     * Total connection count
     */
    getTotalConnectionCount(): Observable<ModelsValue>
    getTotalConnectionCount(opts?: OperationOpts): Observable<AjaxResponse<ModelsValue>>
    getTotalConnectionCount(opts?: OperationOpts): Observable<ModelsValue | AjaxResponse<ModelsValue>> {
        const headers: HttpHeaders = {
        };

        return this.request<ModelsValue>({
            url: '/api/stats/totalConnections',
            method: 'GET',
            headers,
        }, opts?.responseOpts);
    };

}
