name: geopot

services:

  geopot-postgres:
    image: postgres:17-alpine
    container_name: geopot-postgres
    environment:
      - POSTGRES_DB=geopot
      - POSTGRES_USER=geopot
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  geopot-valkey:
    image: valkey/valkey:latest
    container_name: geopot-valkey
    command: /bin/sh -c "redis-server --requirepass ${VALKEY_PASSWORD}"
    volumes:
      - valkey_data:/data
    restart: always

  # geopot:
  #  image: jsfraz/geopot
  #  container_name: geopot
  #  depends_on:
  #    - geopot-postgres
  #  environment:
  #    - POSTGRES_USER=geopot
  #    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #    - POSTGRES_SERVER=geopot-postgres
  #    - POSTGRES_PORT=5432
  #    - POSTGRES_DB=geopot
  #    - VALKEY_PASSWORD=${VALKEY_PASSWORD}
  #    - VALKEY_SERVER=geopot-valkey
  #    - VALKEY_PORT=6379
  #  ports:
  #    - "${PUBLIC_IP}:22:2222"
  #  volumes:
  #    - geopot:/app
  #  restart: always

networks:
  geopot:
    name: geopot

volumes:
  geopot-ssh-server:
  postgres_data:
  valkey_data:
