name: geopot

services:

  geopot-timescaledb:
    image: timescale/timescaledb:latest-pg17
    container_name: geopot-timescaledb
    environment:
      - POSTGRES_DB=geopot
      - POSTGRES_USER=geopot
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/pgdata
    volumes:
      - timescaledb_data:/pgdata
    restart: always

  geopot-valkey:
    image: valkey/valkey:latest
    container_name: geopot-valkey
    command: /bin/sh -c "redis-server --requirepass ${VALKEY_PASSWORD}"
    volumes:
      - valkey_data:/data
    restart: always

  # geopot:
  #  image: jsfraz/geopot
  #  container_name: geopot
  #  depends_on:
  #    - geopot-timescaledb
  #    - geopot-valkey
  #  environment:
  #    - POSTGRES_USER=geopot
  #    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #    - POSTGRES_SERVER=geopot-timescaledb
  #    - POSTGRES_PORT=5432
  #    - POSTGRES_DB=geopot
  #    - VALKEY_PASSWORD=${VALKEY_PASSWORD}
  #    - VALKEY_SERVER=geopot-valkey
  #    - VALKEY_PORT=6379
  #  ports:
  #    - "${PUBLIC_IP}:22:2222"
  #  volumes:
  #    - geopot:/app
  #  restart: always

networks:
  geopot:
    name: geopot

volumes:
  geopot-ssh-server:
  timescaledb_data:
  valkey_data:
