name: geopot

services:

  geopot-timescaledb:
    image: timescale/timescaledb:latest-pg17
    container_name: geopot-timescaledb
    environment:
      - POSTGRES_DB=geopot
      - POSTGRES_USER=geopot
      - POSTGRES_PASSWORD=12345678
      - PGDATA=/pgdata
    volumes:
      - timescaledb_data:/pgdata
    # restart: always

  geopot-valkey:
    image: valkey/valkey:latest
    container_name: geopot-valkey
    command: /bin/sh -c "redis-server --requirepass 12345678"
    volumes:
      - valkey_data:/data
    # restart: always

volumes:
  timescaledb_data:
  valkey_data:
