version: "3.3"
name: lucian

services:

  lucian-postgres:
    image: postgres:alpine
    container_name: lucian-postgres
    environment:
      - POSTGRES_DB=lucian
      - POSTGRES_USER=lucian
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  lucian-redis:
    image: "redis:alpine"
    container_name: lucian-redis
    command: /bin/sh -c "redis-server --requirepass ${REDIS_PASSWORD}"
    volumes:
      - redis_data:/data
    restart: always

  lucian-ssh-server:
    image: jsfraz/lucian-ssh-server
    container_name: lucian-ssh-server
    depends_on:
      - lucian-postgres
    environment:
      - POSTGRES_USER=lucian
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_SERVER=lucian-postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=lucian
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_SERVER=lucian-redis
      - REDIS_PORT=6379
    ports:
      - "${PUBLIC_IP}:22:2222"
    volumes:
      - lucian-ssh-server:/app
    restart: always

networks:
  lucian:
    name: lucian

volumes:
  lucian-ssh-server:
  postgres_data:
  redis_data:
