name: lucian

services:

  lucian-postgres:
    image: postgres:alpine
    container_name: lucian-postgres
    environment:
      - POSTGRES_DB=lucian
      - POSTGRES_USER=lucian
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  lucian-valkey:
    image: valkey/valkey:latest
    container_name: lucian-valkey
    command: /bin/sh -c "redis-server --requirepass ${VALKEY_PASSWORD}"
    volumes:
      - valkey_data:/data

  lucian-ssh-server:
    image: jsfraz/lucian-ssh-server
    container_name: lucian-ssh-server
    depends_on:
      - lucian-postgres
    environment:
      - POSTGRES_USER=lucian
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_SERVER=lucian-postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=lucian
      - VALKEY_PASSWORD=${VALKEY_PASSWORD}
      - VALKEY_SERVER=lucian-valkey
      - VALKEY_PORT=6379
    ports:
      - "${PUBLIC_IP}:22:2222"
    volumes:
      - lucian-ssh-server:/app
    restart: always

networks:
  lucian:
    name: lucian

volumes:
  lucian-ssh-server:
  postgres_data:
  valkey_data:
