// tslint:disable
/**
 * geopot
 * Monitoring SSH login attempts and geolocating remote hosts who failed to login and gathering used credentials.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: razj@josefraz.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface ModelsNumberValue
 */
export interface ModelsNumberValue {
    /**
     * @type {number}
     * @memberof ModelsNumberValue
     */
    value: number;
}
