// tslint:disable
/**
 * geopot
 * Monitoring SSH login attempts and geolocating remote hosts who failed to login and gathering used credentials.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: razj@josefraz.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface ModelsConnection
 */
export interface ModelsConnection {
    /**
     * @type {string}
     * @memberof ModelsConnection
     */
    cityName: string;
    /**
     * @type {string}
     * @memberof ModelsConnection
     */
    continent: string;
    /**
     * @type {string}
     * @memberof ModelsConnection
     */
    continentCode: string;
    /**
     * @type {string}
     * @memberof ModelsConnection
     */
    countryCode: string;
    /**
     * @type {string}
     * @memberof ModelsConnection
     */
    countryName: string;
    /**
     * @type {number}
     * @memberof ModelsConnection
     */
    id: number;
    /**
     * @type {string}
     * @memberof ModelsConnection
     */
    ipAddress: string;
    /**
     * @type {number}
     * @memberof ModelsConnection
     */
    ipVersion: number;
    /**
     * @type {boolean}
     * @memberof ModelsConnection
     */
    isProxy: boolean;
    /**
     * @type {number}
     * @memberof ModelsConnection
     */
    latitude: number;
    /**
     * @type {number}
     * @memberof ModelsConnection
     */
    longitude: number;
    /**
     * @type {string}
     * @memberof ModelsConnection
     */
    password: string;
    /**
     * @type {string}
     * @memberof ModelsConnection
     */
    regionName: string;
    /**
     * @type {string}
     * @memberof ModelsConnection
     */
    timeZone: string;
    /**
     * @type {string}
     * @memberof ModelsConnection
     */
    timestamp: string;
    /**
     * @type {string}
     * @memberof ModelsConnection
     */
    user: string;
    /**
     * @type {string}
     * @memberof ModelsConnection
     */
    zipCode: string;
}
